# 标签页图标
favicon:
  type: "image/x-icon"
  href: "/favicon.ico"

# html lang
language: zh-cn

# canvas 动态背景
canvas_dust: true

# 默认颜色模式 dark / light / auto
# dark 暗色模式
# light 亮色模式
# auto 跟随系统
color: auto

# <body> 背景图片链接
background_image:
  dark: https://ak.hypergryph.com/assets/index/images/ak/pc/bk.jpg # 暗色模式
  light: /img/bk.jpg # 亮色模式

# 导航栏
menu:
  主页: ""
  # Contact: contact/
  归档: archives/
  关于: about/

# 侧边栏
aside:
  in_left: true # 侧边栏在左 true / false
  logo: https://ak.hypergryph.com/assets/index/images/ak/pc/faction/4.png #图片链接，建议 1:1 比例
  dr: https://flacier.us.kg # 侧边栏 Dr. 链接
  icp: # ICP 备案号，与版权声明相同，但会链接到 https://beian.miit.gov.cn/
  copyright: # 版权声明、备案号等，可自定义键值，不想显示则留空
    ©: 2023-2077

# 社交链接
# 格式：链接 || 图标
social:
  GitHub: https://github.com/Fldicoahkiin || fab fa-github
  E-Mail: Flacier@outlook.com || fa fa-envelope
  # Weibo: https://weibo.com/yourname || fab fa-weibo
  # Zhihu: https://www.zhihu.com/people/yourname || fab fa-zhihu

# post 文章页面配置；true / false
post:
  date: true # 是否显示发布日期
  updated: true # 是否显示修改日期
  excerpt: true # 是否在文章中显示摘要内容（<!-- more--> 以上的内容）
  # 文章末显示打赏二维码
  reward:
    # 支付宝 | Alipay: img/Alipay.png
    # 微信 | Wechat: img/WeChat.png
  # 以下两项依赖 hexo-wordcount，请参阅 README 开启
  count: true # 是否显示字数统计
  time: false # 是否显示预计阅读时长

# 文章内目录
toc:
  list_number: true # true / false ；是否显示编号
  max_depth: 6 # 最大目录深度
  min_depth: 1 # 最小目录深度

# 归档页
archives:
  categories_count: true # 是否显示分类总数
  tags_count: true # 是否显示标签总数

# 搜索
search:
  enable: true
  content: true # 若为 false，仅可搜索标题及 metadata
  preload: true # 自动加载搜索数据
  # 设为 post 时，仅可搜索 post 页面
  # 设为 page 时，仅可搜索非 post 页面
  # 设为 all 时，可搜索全部页面
  field: post
  # 设为 html 时，依据 html 文件生成
  # 设为 striptags 时，滤除 html tag
  # 设为 raw 时，依据 markdown 源文件生成
  format: raw
# 背景音乐
bgm:
  enable: false
  autoplay: true
  loop: true
  src: /audio/bgm.mp3

# Vercount
# 详见 https://vercount.one/
vercount:
  enable: true
  sitePV: true # 站点总访问量
  siteUV: true # 站点访客数
  pagePV: true # 页面访问量

# Valine
# 详见 https://valine.js.org
valine:
  enable: false
  app_id: # APP ID
  app_key: # APP KEY
  server_url: # APP DOMAIN（LeanCloud 国际版）

# gitalk
# 详见 https://github.com/gitalk/gitalk
gitalk:
  enable: false
  client_id: # GitHub 应用 Client ID
  client_secret: # GitHub 应用 Client Secret
  repo: # 用于存放评论数据的 GitHub 仓库
  owner: # 该 GitHub 仓库所有者
  admin: [] # 具有写该 GitHub 仓库权限的用户，例如: [adminA,adminB]
  id: # (可选) 页面的唯一标识，例如: location.pathname

# Waline
# 详情: https://waline.js.org/
waline:
  enable: false
  server_url: #Server_Url

# Utterances
# 详见: https://utteranc.es
utterances:
  enable: false
  repo: Fldicoahkiin/utterances-hexo-blog-comments-data # Github 仓库所有者和名称
  issue_term: pathname # 可选值: pathname | url | title | og:title
  theme: github-dark # 可选值: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light

# Giscus
# 详见: https://giscus.app
giscus:
  enable: true
  repo: Fldicoahkiin/hexo-blog-comments-data # Github 仓库所有者和名称，例如: octocat/Hello-World
  repo_id: R_kgDOPRzahg # 仓库 ID，可在 giscus 页面获取
  category: Announcements # discussion 分类名称
  category_id: DIC_kwDOPRzahs4CtYgt # 分类 ID，可在 giscus 页面获取
  mapping: pathname # 页面 ↔️ discussion 映射关系，可选值: pathname | url | title | og:title | specific
  term: # 当 mapping 为 specific 时使用，指定的字符串
  strict: 0 # 是否启用严格标题匹配 0 | 1
  reactions_enabled: 1 # 是否启用主帖子上的反应 0 | 1
  emit_metadata: 0 # 是否输出 discussion 的元数据 0 | 1
  input_position: top # 评论输入框位置，可选值: top | bottom
  theme: preferred_color_scheme # 主题，可选值: light | dark | dark_dimmed | dark_high_contrast | dark_tritanopia | light_high_contrast | light_tritanopia | light_protanopia | dark_protanopia | preferred_color_scheme 或自定义 CSS 链接
  lang: zh-CN # 语言，可选值: de | en | es | fr | gsw | id | it | ja | ko | pl | ro | ru | tr | vi | zh-CN | zh-TW
  loading: lazy
  crossorigin: anonymous

# 图表支持
mermaid:
  enable: true
  version: "9.2.2"

# pjax 支持
pjax:
  enable: true

# 公式前端渲染
mathjax:
  enable: true
  version: "2.6.1"

# 在 `<head>` 标签内引入 CSS 样式表
stylesheets:
  - //unpkg.com/@highlightjs/cdn-assets@11.4.0/styles/atom-one-dark-reasonable.min.css

# 在 `<body>` 尾部引入 JavaScript 脚本
scripts:
  - //unpkg.com/@highlightjs/cdn-assets@11.4.0/highlight.min.js
